# Generated by Django 3.2.9 on 2021-12-06 06:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date', models.DateTimeField()),
                ('cleaning_range', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('cleaning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_groups', to='shop.cleaninggroup')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_records', to='shop.shop')),
            ],
        ),
    ]
