# Generated by Django 3.2.9 on 2021-12-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cleaningrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
