# Generated by Django 3.2.9 on 2021-12-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_smtusers_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtusers',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.smtusers'),
        ),
    ]
