# Generated by Django 3.2.9 on 2021-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_roll',
            field=models.CharField(blank=True, choices=[('M', 'manager'), ('s', 'supervisor'), ('as', 'assistant supervisor'), ('o', 'owner')], default='m', max_length=20, null=True, verbose_name='user roll'),
        ),
    ]
